@startdot
digraph G {
    splines=line
    subgraph cluster_client {
        label="Client";
        node[shape="record",fontname="Consolas",fontsize=12]
        edge[arrowhead="empty"]
        node_Duck [
             label="{Duck
             |<f0>FlyBehavior flyBehavior\n QuackBehavior quackBehavior
             |swim()\ldisplay()\lperformQuack()\lperformFly()\lsetFlyBehavior()\lsetQuackBehavior()\l}"
        ]

        node_MallardDuck[label="{MallardDuck|display()\l}"]
        node_MallardDuck->node_Duck

        node_RedheadDuck[label="{RedheadDuck|display()\l}"]
        node_RedheadDuck->node_Duck

        node_RubberDuck[label="{RubberDuck|display()\l}"]
        node_RubberDuck->node_Duck

        node_DecoyDuck[label="{DecoyDuck|display()\l}"]
        node_DecoyDuck->node_Duck
    }

    subgraph cluster_fly {
        label="Encapsulated fly behavior"
        node[shape="record",fontname="Consolas",fontsize=12]
        edge[arrowhead="empty", style="dashed"]

        node_FlyBehavior[label="{\<\<interface\>\>\nFlyBehavior|fly()\l}"]
        node_FlyWithWings[label="{FlyWithWings|fly()\l}"]
        node_FlyWithWings->node_FlyBehavior

        node_FlyNoWay[label="{FlyNoWay|fly()\l}"]
        node_FlyNoWay->node_FlyBehavior

    }

    subgraph cluster_quack {
        label="Encapsulated quack behavior"
        node[shape="record",fontname="Consolas",fontsize=12]
        edge[arrowhead="empty", style="dashed"]

        node_QuackBehavior[label="{\<\<interface\>\>\nQuackBehavior|quack()\l}"]
        node_Quack[label="{Quack|quack()\l}"]
        node_Squeak[label="{Squeak|quack()\l}"]
        node_MuteQuack[label="{MuteQuack|quack()\l}"]

        node_Quack->node_QuackBehavior
        node_Squeak->node_QuackBehavior
        node_MuteQuack->node_QuackBehavior

    }

    node_Duck:f0->node_FlyBehavior;
    node_Duck:f0->node_QuackBehavior;
}
@enddot