@startdot
digraph s {
    rankdir = BT;

    edge[arrowhead=empty];
    node[shape="record", fontname="Consolas,Monaco"];

    node_beverage[label="{Beverage|description\l|getDescription()\lcost()\l}"];

    node_houseBlend[label="{<d0>HouseBlend|cost()\l}"];
    node_darkRoast[label="{<d0>nDarkRoast|cost()\l}"];
    node_decaf[label="{<d0>Decaf|cost()\l}"];
    node_espresso[label="{<d0>Espresso|cost()\l}"];


    node_houseBlend  -> node_beverage;
    node_darkRoast  ->  node_beverage;
    node_decaf       -> node_beverage;
    node_espresso   ->  node_beverage;

    node_condimentDecorator[label="{<f1>CondimentDecorator|getDescription()\l}"];

    node_condimentDecorator -> node_beverage;
    node_condimentDecorator:f1 -> node_beverage[label="component",arrowhead="vee"]

    node_milk[label="{<d0>Milk|Beverage beverage\l|cost()\lgetDescription()\l}"];
    node_Mocha[label="{<d0>Mocha|Beverage beverage\l|cost()\lgetDescription()\l}"];
    node_soy[label="{<d0>Soy|Beverage beverage\l|cost()\lgetDescription()\l}"];
    node_whip[label="{<d0>Whip|Beverage beverage\l|cost()\lgetDescription()\l}"];

    node_milk->node_condimentDecorator
    node_Mocha->node_condimentDecorator
    node_soy->node_condimentDecorator
    node_whip->node_condimentDecorator
}
@enddot